schema_version: 1

context:
  version: "0.38.0"

package:
  name: regal
  version: ${{ version }}

source:
  url: https://github.com/StyraInc/regal/archive/v${{ version }}.tar.gz
  sha256: d9535e9285ce883c8dfc190749eba7c20468ecaeb8d4cce2dbdd30a140fefa87

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - regal --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Regal is a linter and language server for Rego, bringing your policy development experience to the next level!
  homepage: https://github.com/StyraInc/regal
  repository: https://github.com/StyraInc/regal

extra:
  recipe-maintainers:
    - danielnachun
